model_dict={
    'Qwen2.5-72B-Instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25-72b-instruct-1.bcloud.hd2a-h.ml.baichuan-inc.com:80/v1',
    },
    'Qwen2.5-VL-72B-Instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25-vl-72b-instruct.bcloud.hd2a-h.ml.baichuan-inc.com:80/v1',
    },
    'gpt-4o-2024-05-13':{
        'api_key':"sk-A0TVfHXPKrL6ahM4WVa8RAJfjWYrhHD8vIpN7fSX7IiT5fG7",
        'base_url':'http://172.23.3.27/v1',
    },
    'InternVL2_5-78B':{
        'api_key':"EMPTY",
        'base_url':'http://internvl-25-78b-lc.bcloud.hd2a-h.ml.baichuan-inc.com:80/v1',
    },
    'MiniCPM-o-2_6':{
        'api_key':"EMPTY",
        'base_url':'http://lc-minicpm-o-2-6.bcloud.hd2a-h.ml.baichuan-inc.com:80/v1',
    },
    'internvl25_mpo_78b':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl2-5-78b-mpo-judge.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },
    'Qwen2-VL-72B-Instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen2-vl-72b-instruct.bcloud.hd2a-h.ml.baichuan-inc.com:80/v1',
    },
    'internvl25_mpo_8b':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl2-5-8b-mpo.prod.ppio.bc-inner.com:80/v1',
    },
    'qwen25_vl_7b_instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25-7b.prod.ppio.bc-inner.com:80/v1',
    },
    "qwen25_vl_72b_instruct_judgemodel" : {
        "base_url" :"http://lc-qwen25-vl-72b-instruct-judge.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1",
        "api_key" : "EMPTY",
        "model_name_path":"",
        "inference_vllm":0
    },
    'gemini-2.0-flash-thinking-exp-01-21':{
        'api_key':"sk-A0TVfHXPKrL6ahM4WVa8RAJfjWYrhHD8vIpN7fSX7IiT5fG7",
        'base_url':'http://172.23.3.27/v1',
    }, 
    'internvl25_mpo_8b':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl25-mpo-8b.prod.ppio.bc-inner.com:80/v1',
    },
    'internvl25_8b':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl25-8b.prod.ppio.bc-inner.com:80/v1',
    },
    'qwen2_vl_7b_instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen2-7b-1.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },
    'qwen2_vl_72b_instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen2-vl-72b-instruct-judge.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },
    'qwen25_vl_7b_instruct':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25-7b.prod.ppio.bc-inner.com:80/v1',
    },
    'internvl25_78b':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl2-5-78b-judge-1.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },
    'doubao-1-5-vision-pro-32k-250115':{
        'api_key':"86182a69-87bf-442d-9a2e-204abcd26cd0",
        'base_url':'https://ark.cn-beijing.volces.com/api/v3',
    },
    'prm-v1':{
        'api_key':"EMPTY",
        'base_url':'http://lc-pmrv1.prod.ppio.bc-inner.com:80/v1',
    },
    'visual_prm':{
        'api_key':"EMPTY",
        'base_url':'http://lc-internvl25-mpo-8b.prod.ppio.bc-inner.com:80/v1',
    },
    'prm-v2':{
        'api_key':"EMPTY",
        'base_url':'http://lc-pmrv2.prod.ppio.bc-inner.com:80/v1',
    },
    'qwen25vlinstruct_scimcts04244e6':{
        'api_key':"EMPTY",
        'base_url':'http://zcl-qwen25vlinstruct-scimcts04244e6.prod.ppio.bc-inner.com:80/v1',
    },
    'qwen25vlinstruct-scimcts04244e6-prm':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25vlinstruct-scimcts04244e6-prm.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },
    'qwen25vlinstruct-scimcts04241e5-prm':{
        'api_key':"EMPTY",
        'base_url':'http://lc-qwen25vlinstruct-scimcts04241e5-prm.bcloud.hb1b-h20.ml.baichuan-inc.com:80/v1',
    },


}